-- AlterEnum
ALTER TYPE "ProductType" ADD VALUE 'JEWELRY';
ALTER TYPE "ProductType" ADD VALUE 'TRAFFIC_SERVICE';
ALTER TYPE "ProductType" ADD VALUE 'TRUCK_LOAN';
ALTER TYPE "ProductType" ADD VALUE 'GOLF_CAR';
ALTER TYPE "ProductType" ADD VALUE 'WATERCRAFT';
ALTER TYPE "ProductType" ADD VALUE 'EDUCATION';
ALTER TYPE "ProductType" ADD VALUE 'GREEN_FINANCE';
ALTER TYPE "ProductType" ADD VALUE 'TRAVEL';
